batch_size: 512
epochs: 100
eval_every_n_epochs: 1
fine_tune_from: ''
log_every_n_steps: 10
weight_decay: 10e-6
fp16_precision: False
n_gpu: 2
gpu_ids: (0,1)
back_bone: swintransformer


model:
  out_dim: 256
  base_model: "swin_tiny_patch4_window7_224"

dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 0
  valid_size: 0.1

loss:
  temperature: 0.5
  use_cosine_similarity: True
